### ISSUE TITLE
Timetracker consuming 30% of cpu resources

### ISSUE THREAD

**Issue by Demitrix2k** [JTNDev/galaxy-integration-gc#6]
As title stated, does not matter which i game i launch the time tracker is an all time high consumer of cpu resources, even with the game closed its still running sucking resources.
![457345677](https://user-images.githubusercontent.com/38674952/66268661-ed1a0580-e83f-11e9-91d6-893a0e2cb67c.jpg)

**Comment by JTNDev** [comment]
Wow, I'll look into another method

**Comment by Demitrix2k** [comment]
My alternative method to a plugin is to use a bat file and run something akin to this
`@echo off
echo Keeping Window Active for GOG Time Tracking
cd /D "G:\Emulator\Gamecube & Wii\Dolphin-x64"
cmd.exe /c Dolphin.exe "G:\Emulator\Gamecube & Wii\Gamecube\Pokemon Colosseum.gcm" 
the echo is uneccesary it seems for this, but does the job for other emulators such as project64 so i have time tracked.



`

**Comment by JTNDev** [comment]
Closed as fixed [here](https://github.com/JTNDev/galaxy-integration-gc/commit/8cb2fd9f42c6653d6c0bfba534e03ba919f84eae)

**Comment by JTNDev** [comment]
The issue was I was using a while loop, so it would run as much as possible so it was using as much CPU as it wanted. I fixed it by adding a sleep function inside of the while loop so it'll only check if it's running every second and it went from ~30% on my i5-3450 to around 0.7%, which I could make even lower if I check every 30 seconds or so
